### ISSUE TITLE
MP4 H264 extracted: Corrupt video codec on pond5

### ISSUE THREAD

**Issue by firepol** [mifi/lossless-cut#231]
Hi, I use lossless-cut to cut my DJI drone footage shot with the DJI Mavic Air, but I suppose this problem affects all files with the same codec.

If I skip some seconds from the file and extract a portion in the middle, e.g. in a 50s video I skip the first 10 seconds and select from 0:10 to 0:50 and I upload the extracted file to pond5 (a website where you can sell your footage) pond5 gives me this error:

```
PROCESSING FAILED
Corrupt video codec. Please see our upload guidelines.
```

I think that the initial part of an h264 ecoded MP4 contains information not included when extracting a portion not including the initial part...

The file works just fine with VLC, I can play it without problems.

I tried to check the file with ffprobe, but can't see any error.

Ideas?

**Comment by firepol** [comment]
I contacted pond5 support and I was pointed to the right direction:

So here my findings: if I use ffmpeg to fix the second part (as explained above) of a file extracted with lossless-cut, like this, and upload the fixed file to pond5, I don't get the processing failed error:

```
ffmpeg -err_detect ignore_err -i DJI_0176.MP4 -c copy DJI_0176_fixed.mp4
```

I binary compared with Beyond Compare the file extracted by lossless-cut and the one fixed by ffmpeg, and there is a difference in the end, see screenshot:

![image](https://user-images.githubusercontent.com/1702718/70595310-a5d03c80-1c15-11ea-8b44-3de4aa97c346.png)

So I think lossless-cut should integrate a fix, so that files extracted without containing the initial part of the original source file have the proper information.

In my case the corrupt file ends with: Lavf56.15.102
The fixed version ends with: Lavf58.29.100

I really don't know what that means, but I hope the developer in charge can make a food use of my little investigation. Cheers

**Comment by firepol** [comment]
I did fix 2 more files and in both case, the ending of the corrupt files was: Lavf58.33.100
Fixed version: Lavf58.29.100

I'm trying to write a powershell script to automate this. I think you should fix this in lossless-cut. Thanks

**Comment by mifi** [comment]
Thanks for the heads up. So you're saying that even using `ffmpeg -err_detect ignore_err -i DJI_0176.MP4 -c copy DJI_0176_fixed.mp4 ` doesn't solve the problem you had when uploading?

**Comment by mifi** [comment]
I have upgraded ffmpeg version included in LC. maybe it helps... or if you could try to cut with newest ffmpeg from the command line and see if it works, it would be great

**Comment by mifi** [comment]
closing due to lack of activity
